FROM	ubuntu:18.04
ARG	UNAME=user
ARG	UID=1000
ARG	GID=1000
RUN	groupadd -g $GID -o $UNAME
RUN	useradd -m -u $UID -g $GID -o -s /bin/bash $UNAME
RUN	apt update && \
	apt install -y x11-apps && \
	rm -fr /var/lib/apt/lists/*
ENV 	DISPLAY :0
USER $UNAME

ENTRYPOINT ["/bin/sh", "-c", "$0 \"$@\"", "xeyes"]
